---
title: "Final Project"
author: "Ali Thursland"
date: "11/20/2018"
output: html_document
---

```{r setup, warning=FALSE, echo=FALSE, message=FALSE}
#Setup
library("dplyr")
library("ggplot2")
library("broom")
library("knitr")
library("cowplot")
library("readr")
library("dslabs")
```

```{r data}
#Read file
airbnb <- read.csv("/Users/alithursland/Documents/STA 210/airbnb.csv")
```

```{r manipulating-data}
#Make new variable has_reviews
airbnb <- airbnb %>% 
  mutate(has_reviews = case_when( 
    number_of_reviews == 0 ~ 0, 
    number_of_reviews > 0 ~ 1)
  )

#Make NAs = 0 for security_deposit
airbnb <- airbnb %>% 
  mutate(security_deposit = if_else(is.na(security_deposit),0,security_deposit))

#Make NAs = 0 for cleaning_fee
airbnb <- airbnb %>% 
  mutate(cleaning_fee = if_else(is.na(cleaning_fee),0,cleaning_fee))

#Make NAs = 0 for review_scores_rating
airbnb <- airbnb %>% 
  mutate(review_scores_rating = case_when(
    is.na(review_scores_rating) ~ 0, 
    !is.na(review_scores_rating) ~ review_scores_rating)
    )

#Make NAs = 0 for review_scores_accuracy
airbnb <- airbnb %>% 
  mutate(review_scores_accuracy = case_when(
    is.na(review_scores_accuracy) ~ 0, 
    !is.na(review_scores_accuracy) ~ review_scores_accuracy)
    )

#Make NAs = 0 for review_scores_cleanliness
airbnb <- airbnb %>% 
  mutate(review_scores_cleanliness = case_when( 
    is.na(review_scores_cleanliness) ~ 0, 
    !is.na(review_scores_cleanliness) ~ review_scores_cleanliness)
    )

#Make NAs = 0 for review_scores_checkin
airbnb <- airbnb %>% 
  mutate(review_scores_checkin = case_when( 
    is.na(review_scores_checkin) ~ 0, 
    !is.na(review_scores_checkin) ~ review_scores_checkin)
    )

#Make NAs = 0 for review_scores_communcation
airbnb <- airbnb %>% 
  mutate(review_scores_communication = case_when( 
    is.na(review_scores_communication) ~ 0, 
    !is.na(review_scores_communication) ~ review_scores_communication)
    )

#Make NAs = 0 for review_sores_location 
airbnb <- airbnb %>% 
  mutate(review_scores_location = case_when( 
    is.na(review_scores_location) ~ 0, 
    !is.na(review_scores_location) ~ review_scores_location)
    )

#Make NAs = 0 for review_scores_value
airbnb <- airbnb %>% 
  mutate(review_scores_value = case_when( 
    is.na(review_scores_value) ~ 0, 
    !is.na(review_scores_value) ~ review_scores_value)
    )

#Make NAs = 0 for reviews_per_month
airbnb <- airbnb %>% 
  mutate(reviews_per_month = case_when( 
    is.na(reviews_per_month) ~ 0, 
    !is.na(reviews_per_month) ~ reviews_per_month)
    )
```

```{r omit-na}
#Omit all observations with NAs 
airbnb <- airbnb[complete.cases(airbnb),]
```

Question of interest: How can we produce a model that accurately predicts the listed nightly price for an Airbnb in Asheville, NC?
